apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway-service
spec:
  replicas: 1 # Number of pods to run for high availability
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: nud-api-gateway-service:latest # Replace with your Docker image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000 # The port your application listens to
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_GATEWAY_PORT
              value: "5000"
            - name: USER_SERVICE_URL
              value: "user-service:5002"
            - name: ACTIVITY_SERVICE_URL
              value: "activity-service:5003"
            - name: REVIEW_SERVICE_URL
              value: "review-service:5004"
            - name: FRIEND_MATCHING_SERVICE_URL
              value: "friend-matching-service:5005"
            - name: JWT_SECRET
              value: "secret"
            - name: USER_PROTO_PATH
              value: "../proto/user.proto"
            - name: REVIEW_PROTO_PATH
              value: "../proto/review.proto"
            - name: ACTIVITY_PROTO_PATH
              value: "../proto/activity.proto"
            - name: FRIEND_MATCHING_PROTO_PATH
              value: "../proto/friendmatching.proto"
            - name: RMQ_URL
              value: "amqp://rabbitmq:5672"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe: # Checks if the gRPC server port is open
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe: # Checks if the gRPC server port is ready to accept traffic
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: NodePort
  selector:
    app: api-gateway-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
