apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1 # Number of pods to run for high availability
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: tumktp/nud-user-service:latest # Replace with your Docker image
          imagePullPolicy: Never
          ports:
            - containerPort: 5002 # The port your application listens to
          env:
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              value: "secret"
            - name: USER_SERVICE_URL
              value: "0.0.0.0:5002"
            - name: DATABASE_HOST
              value: "user-service-mysql"
            - name: MYSQL_ROOT_USERNAME
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: DATABASE_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "nud-user-service"
            - name: USER_PROTO_PATH
              value: "./proto/user.proto"
            - name: RMQ_URL
              value: "amqp://rabbitmq:5672"
          livenessProbe: # Checks if the gRPC server port is open
            grpc:
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe: # Checks if the gRPC server port is ready to accept traffic
            grpc:
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP # Use ClusterIP for internal access only or NodePort for limited external access
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  selector:
    app: user-service

# Add ExternalName service for mysql database
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-mysql
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 3306 # The port to expose
      targetPort: 3306 # The port where MySQL is running on your localhost
