# Stage 1: Build the NestJS app
FROM node:20 AS builder

# Set working directory
WORKDIR /app

# Copy the proto folder
COPY proto ./proto

# Copy dependency files and install dependencies
COPY friend-matching-service/package*.json friend-matching-service/yarn.lock ./friend-matching-service/
RUN cd friend-matching-service && yarn

# Copy the rest of the app source code
COPY friend-matching-service ./friend-matching-service

# Build the app
RUN cd friend-matching-service && yarn build

# Stage 2: Run the NestJS app
FROM node:20

# Set working directory
WORKDIR /app

# Copy only necessary files from the builder stage
COPY --from=builder /app/friend-matching-service/package*.json ./
COPY --from=builder /app/friend-matching-service/dist ./dist
COPY --from=builder /app/friend-matching-service/node_modules ./node_modules

# Copy the proto folder from the builder stage
COPY --from=builder /app/proto ./dist/proto

# Expose the port the app runs on
EXPOSE 5005

# Set NODE_ENV to production
ENV NODE_ENV=production

# Start the app
CMD ["node", "dist/main"]
