version: '3.8'

services:
  nestjs_api:
    build: Dockerfile
    ports:
      - "3000:3000"
    
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - nud_user_service:/var/lib/mysql
    networks:
      - app-network

volumes:
  nud_user_service:
    driver: local

networks:
  app-network:
    driver: bridge
